import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import pandas as pd, json
from datetime import datetime as dt, timedelta
from trading_core import load_kite_session, STOCK_REGISTRY, scan_symbol, scan_anchor_bcd_breakout, find_anchor_bullish_engulfing, find_anchor_ll_sweep, find_anchor_hammer_baby, find_anchor_bullish_harami, find_anchor_two_higher_highs, resolve_option_strikes
from kiteconnect import KiteConnect
import trade_db

api_key, access_token = load_kite_session()
kite = KiteConnect(api_key=api_key)
kite.set_access_token(access_token)

instruments = pd.DataFrame(kite.instruments('NFO'))

config = STOCK_REGISTRY["HCLTECH"]
ref_now = dt.now()
from_entry = (ref_now - timedelta(days=10)).strftime("%Y-%m-%d")
to_entry = ref_now.strftime("%Y-%m-%d")

entry_scanners = [("Setup_1_Anchor_BCD", scan_anchor_bcd_breakout)]
anchor_scanners = [("A1", find_anchor_bullish_engulfing)]

def mock_log(*args, **kwargs):
    pass

trades = scan_symbol(kite, "HCLTECH", config, from_entry, to_entry, from_entry, to_entry,
                     entry_scanners, anchor_scanners,
                     lambda sym, sp, step, opt, r: resolve_option_strikes(instruments, sym, sp, step, opt, r),
                     "nifty50", "15minute", "30minute", "15minute",
                     {}, trade_db.threading.Lock(), trade_db, 3, mock_log)

print("\n--- Trades generated by scan_symbol for HCLTECH ---")
for t in trades:
    print(f"Symbol: {t['symbol']} | Contract: {t['contract']} | Pattern: {t['pattern']} | Entry Time: {t['entry_time']} | Entry Spot: {t['entry_spot']}")
